### ISSUE TITLE
Send a request to API with select option parameters

### ISSUE THREAD

**Issue by cod-lvr** [cod-lvr/REST-Countries-API-with-color-theme-switcher-component-#1]
Send a request to API with select option parameters in Home page, you can select a region that's can change request of API and reload the React component.

**Comment by shikhar13012001** [comment]
I would like to work on this issue @cod-lvr

**Comment by cod-lvr** [comment]
sure, go ahead and please comment your code. @shikhar13012001

**Comment by Potato-29** [comment]
I would like to try working on this enhancement

**Comment by cod-lvr** [comment]
sure, you can @Potato-29 . Already open new issue at [#2](https://github.com/cod-lvr/REST-Countries-API-with-color-theme-switcher-component-/issues/2)

**Comment by ztlaw** [comment]
Hello, I would like to try and work on this issue @cod-lvr. thank you.
