### ISSUE TITLE
Style CountryDetails page using tailwind

### ISSUE THREAD

**Issue by cod-lvr** [cod-lvr/REST-Countries-API-with-color-theme-switcher-component-#2]
Style Country Details page using tailwind depending on props data from  API respond on server as designed page.
Attached example of API response  with design page example.

![Screen Shot 2022-06-18 at 12 09 14 AM](https://user-images.githubusercontent.com/79340509/174407749-435f2668-1e11-4e93-9ffb-ba17f5a792df.png)
![mobile-design-detail-light](https://user-images.githubusercontent.com/79340509/174407798-d759a03d-5e6f-4fbc-b646-c78f156bba6a.jpg)

**Comment by Potato-29** [comment]
Hi, I would like to work on this

**Comment by cod-lvr** [comment]
Sure, @Potato-29, please comment your code
